### ISSUE TITLE
New Github Code Search mode

### ISSUE THREAD

**Issue by eduwass** [Legend-Master/open-github-in-vscode#2]
Hi @Legend-Master 

just an FYI, looks like Github have released this new feature (beta):

- https://github.blog/changelog/2023-02-23-no-more-waitlist-code-search-and-code-view-are-available-to-all-in-public-beta/
- https://docs.github.com/en/repositories/working-with-files/managing-files/navigating-files-with-the-new-code-view

Here's an example URL:
https://github.com/facebook/react/blob/ca2cf319fdfcf6e5f048e082f5169bc1b849c129/packages/react/src/ReactMemo.js#L37

And how it looks like once the feature is enabled:
<img width="1451" alt="CleanShot 2023-02-24 at 17 01 03@2x" src="https://user-images.githubusercontent.com/1070495/221226450-4f28dbaa-8696-460e-bed6-74c0d3870898.png">

Would be nice to add compatibility with this new mode in the future.

Thanks!

**Comment by Legend-Master** [comment]
Guess I'll wait till it's released first since things can change a lot in the beta (at least that's what I have experienced when modding a game)

Thank for the heads up tho

**Comment by eduwass** [comment]
Absolutely, that makes total sense, just posting so it's on the radar 👍

**Comment by Legend-Master** [comment]
To be honest we can always just override the behavior of "." (which will redirect you to the web vscode) to open the desktop version

**Comment by eduwass** [comment]
@Legend-Master JFYI looks like this was recently released (not beta anymore).

**Comment by Legend-Master** [comment]
Yes, and I just made some changes at b9d9a5207d643d74f07e886a0f70f1e0350396d1

Need some more changes and testing for supporting Refined Github and doing some optimizations though

**Comment by Legend-Master** [comment]
Refined Github seems not catching up yet, guess I'll do a minimum support until they catch up

**Comment by eduwass** [comment]
Sounds good, thanks again @Legend-Master
